sudo: required
services: docker
before_install:
  # Force install of latest docker (Travis includes Docker APT repository but doesn't update)
  - sudo apt-get update -qq && sudo apt-get -y --force-yes -o Dpkg::Options::="--force-confnew" install $APT_DOCKER_PKG && docker -v
script:
  - docker build .
